name: My first github Action
on: [push]
jobs:
  build-app:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          width:
            node-version: "14.17.0"
        - name: Build the project
          run: npm run build
        - name: Build finish
          run: echo "Project build"
